CC = gcc
ARCH_FLAGS ?= -march=native
FLAGS = -DNDEBUG -Wall -Wno-unused-function -Wno-unused-result -funroll-all-loops $(ARCH_FLAGS) -lm
DEBUG_FLAGS = -O1 -g $(FLAGS)
INCLUDE_DIRS = $(addprefix $(MOSFHET_DIR), /include)
OPT_FLAGS = -O3 -fwhole-program -flto  $(FLAGS)
LIB_FLAGS = -O3 $(FLAGS)
__SRC = keyswitch.c bootstrap.c bootstrap_ga.c tlwe.c trlwe.c trgsw.c misc.c polynomial.c register.c pvwtlwe.c sha3/fips202.c fft/karatsuba.c
ENABLE_PVW_TMLWE ?= false
MAT_TRGSW_AVX512_SMALLR_SPECIALIZED ?= false
ifeq ($(MAT_TRGSW_AVX512_SMALLR_SPECIALIZED),true)
	FLAGS += -DMAT_TRGSW_AVX512_SMALLR_SPECIALIZED
	ENABLE_PVW_TMLWE := true
endif
SAB_PVW_KERNEL_TEST ?= false
ifeq ($(SAB_PVW_KERNEL_TEST),true)
	FLAGS += -DSAB_PVW_KERNEL_TEST
	ENABLE_PVW_TMLWE := true
endif
SAB_PVW_TARGET_TEST ?= false
ifeq ($(SAB_PVW_TARGET_TEST),true)
	FLAGS += -DSAB_PVW_TARGET_TEST
	ENABLE_PVW_TMLWE := true
endif
SAB_PVW_BENCH ?= false
SAB_PVW_BENCH_R ?= 2
SAB_PVW_BENCH_REPS ?= 3
ifeq ($(SAB_PVW_BENCH),true)
	FLAGS += -DSAB_PVW_BENCH
	FLAGS += -DSAB_PVW_BENCH_R=$(SAB_PVW_BENCH_R)
	FLAGS += -DSAB_PVW_BENCH_REPS=$(SAB_PVW_BENCH_REPS)
	ENABLE_PVW_TMLWE := true
endif
SAB_PVW_NOISE_TEST ?= false
SAB_PVW_NOISE_R ?= 2
SAB_PVW_NOISE_TRIALS ?= 3
SAB_PVW_NOISE_MAX_LOG2_GAP ?= 4.0
ifeq ($(SAB_PVW_NOISE_TEST),true)
	FLAGS += -DSAB_PVW_NOISE_TEST
	FLAGS += -DSAB_PVW_NOISE_R=$(SAB_PVW_NOISE_R)
	FLAGS += -DSAB_PVW_NOISE_TRIALS=$(SAB_PVW_NOISE_TRIALS)
	FLAGS += -DSAB_PVW_NOISE_MAX_LOG2_GAP=$(SAB_PVW_NOISE_MAX_LOG2_GAP)
	ENABLE_PVW_TMLWE := true
endif
SAB_PVW_STAGE_NOISE_TEST ?= false
ifeq ($(SAB_PVW_STAGE_NOISE_TEST),true)
	FLAGS += -DSAB_PVW_STAGE_NOISE_TEST
	FLAGS += -DSAB_PVW_NOISE_R=$(SAB_PVW_NOISE_R)
	FLAGS += -DSAB_PVW_NOISE_TRIALS=$(SAB_PVW_NOISE_TRIALS)
	FLAGS += -DSAB_PVW_NOISE_MAX_LOG2_GAP=$(SAB_PVW_NOISE_MAX_LOG2_GAP)
	ENABLE_PVW_TMLWE := true
endif
SAB_PVW_RESOURCE_TEST ?= false
SAB_PVW_RESOURCE_R ?= 2
ifeq ($(SAB_PVW_RESOURCE_TEST),true)
	FLAGS += -DSAB_PVW_RESOURCE_TEST
	FLAGS += -DSAB_PVW_RESOURCE_R=$(SAB_PVW_RESOURCE_R)
	ENABLE_PVW_TMLWE := true
endif
SAB_PVW_POSTPROC_PROFILE ?= false
ifeq ($(SAB_PVW_POSTPROC_PROFILE),true)
	FLAGS += -DSAB_PVW_POSTPROC_PROFILE
	ENABLE_PVW_TMLWE := true
endif
ifeq ($(ENABLE_PVW_TMLWE),true)
	__SRC += pvwtmlwe.c mattrgsw.c
endif
SAB_PROFILE ?= false
ifeq ($(SAB_PROFILE),true)
	FLAGS += -DSAB_PROFILE
endif
SAB_MICROBENCH ?= false
ifeq ($(SAB_MICROBENCH),true)
	FLAGS += -DSAB_MICROBENCH
endif
LIBS = 
LD_LIBS =
BUILD_LIBS = 
TEST_FLAGS = $(OPT_FLAGS)
MOSFHET_DETERMINISTIC_RNG ?= false
MOSFHET_TEST_RNG_SEED ?= 1
ifeq ($(MOSFHET_DETERMINISTIC_RNG),true)
	FLAGS += -DMOSFHET_DETERMINISTIC_RNG
	FLAGS += -DMOSFHET_TEST_RNG_SEED=$(MOSFHET_TEST_RNG_SEED)
endif
# FFT_LIB = spqlios_avx512
# A_PRNG = vaes
# ENABLE_VAES = true
FFT_LIB = spqlios
A_PRNG = none
ENABLE_VAES = false

ifeq ($(A_PRNG),shake)
	FLAGS += -DUSE_SHAKE -DUSE_COMPRESSED_TRLWE
	__SRC += trlwe_compressed.c
else ifeq ($(A_PRNG),vaes)
	__SRC += trlwe_compressed_vaes.c
	FLAGS += -DUSE_COMPRESSED_TRLWE
else ifeq ($(A_PRNG),xoshiro)
	__SRC += trlwe_compressed.c
	FLAGS += -DUSE_COMPRESSED_TRLWE
endif

ifdef TORUS32
 FLAGS += -DTORUS32
endif


ifeq ($(FFT_LIB),ffnt)
	PORTABLE_BUILD := 1
endif

ifdef PORTABLE_BUILD
	FFT_LIB=ffnt
	FLAGS += -DUSE_SHAKE
else
  __SRC += ./rnd/aes_rng.c
endif

ifeq ($(ENABLE_VAES), true)
	FLAGS += -DVAES_OPT
endif

ifeq ($(FFT_LIB),spqlios)
	FLAGS += -DUSE_SPQLIOS
	__SRC += ./fft/spqlios/spqlios-fft-fma.s ./fft/spqlios/spqlios-ifft-fma.s ./fft/spqlios/spqlios-fft-impl.c ./fft/spqlios/fft_processor_spqlios.c
else ifeq ($(FFT_LIB),spqlios_avx512)
	FLAGS += -DUSE_SPQLIOS -DAVX512_OPT
	__SRC += ./fft/spqlios/spqlios-fft-avx512.s ./fft/spqlios/spqlios-ifft-avx512.s ./fft/spqlios/spqlios-fft-impl-avx512.c ./fft/spqlios/fft_processor_spqlios.c
else ifeq ($(FFT_LIB),ffnt_opt)
	FLAGS += -DFMA_OPT
  __SRC += ./fft/ffnt/ffnt.c
else
	FLAGS += -DPORTABLE_BUILD
  __SRC += ./fft/ffnt/ffnt.c
endif

SRC_MOSFHET = $(addprefix $(MOSFHET_DIR)/src/, $(__SRC))
INCLUDE_FLAGS = $(addprefix -I, $(INCLUDE_DIRS))
FLAGS += $(INCLUDE_FLAGS)
